# Server settings (ServerProperties)
server:
  port: 4000
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs



spring:
  data:
      mongodb.host: 139.196.83.10
      mongodb.port: 26117
      mongodb.uri: mongodb://huangxiaoxu:huangxiaoxu@139.196.83.10:26117/zrxlaw
      mongo.repositories.enabled: true